### ISSUE TITLE
API Inconsistency: RaygunBreadcrumbLevel

### ISSUE THREAD

**Issue by luisguerrerolab** [MindscapeHQ/raygun4xamarin-samples#4]
### Summary

In the latest version of Raygun4Xamarin.Forms, both levels Error and None share the same value:

```
public enum RaygunBreadcrumbLevel
{
	None = 0,
	[EnumMember (Value = "error")]
	Error = 0,
	[EnumMember (Value = "warning")]
	Warning = 1,
	[EnumMember (Value = "info")]
	Info = 2,
	[EnumMember (Value = "debug")]
	Debug = 3
}
```

Causing the breadcrumb's icon background color to appear gray instead of red in the Breadcrumbs section of the crash report.

### Relevant logs/screenshots

Breadcrumb as shown in the Breadcrumbs section:
<img width="925" alt="Screen Shot 2019-10-28 at 15 19 46" src="https://user-images.githubusercontent.com/5489034/67718981-88f9e580-f996-11e9-8008-ec72c673b6da.png">

JSON object for that element (from Raw data):
```
...
{
    "Message": "Manual Error",
    "Level": "None",
    "Type": "manual",
    "Timestamp": 1572296843208
},
...
```

Generated breadcrumb in C#:
```
var breadcrumb = new RaygunBreadcrumb();
breadcrumb.Message = "Manual Error";
breadcrumb.Level = RaygunBreadcrumbLevel.Error;
```

**Comment by mduncan26** [comment]
Thank you for bringing this to our attention. We have released a fix to address this problem. It is available in version 1.0.2 of the provider.

Please feel free to open another issue if it continues after updating.
