### ISSUE TITLE
API-Dashboard inconsistency: breadcrumb color doesn't match its corresponding level

### ISSUE THREAD

**Issue by luisguerrerolab** [MindscapeHQ/raygun4xamarin-samples#7]
On version `1.0.3` I found that in the Crash Reporting dashboard none of the colors match their corresponding breadcrumb level.

Generated breadcrumbs in code:
```
RaygunClient.Current.RecordBreadcrumb("Level: error", RaygunBreadcrumbType.Manual, RaygunBreadcrumbLevel.Error);
RaygunClient.Current.RecordBreadcrumb("Level: warning", RaygunBreadcrumbType.Manual, RaygunBreadcrumbLevel.Warning);
RaygunClient.Current.RecordBreadcrumb("Level; debug", RaygunBreadcrumbType.Manual, RaygunBreadcrumbLevel.Debug);
RaygunClient.Current.RecordBreadcrumb("Level: info", RaygunBreadcrumbType.Manual, RaygunBreadcrumbLevel.Info);
RaygunClient.Current.RecordBreadcrumb("Level: none", RaygunBreadcrumbType.Manual, RaygunBreadcrumbLevel.None);
```

Result in Crash Reporting dashboard:
<img width="906" alt="Screen Shot 2019-10-30 at 21 15 36" src="https://user-images.githubusercontent.com/5489034/67916170-78926800-fb5a-11e9-853e-bf339332cc44.png">

**Comment by mduncan26** [comment]
Hi @albertoms 

We have not been able to reproduce this scenario. Can you please try cleaning your solution, restoring NuGet packages and build the solution again.

Thank you,
Mitchell.

**Comment by luisguerrerolab** [comment]
Sorry, @mduncan26, that was my mistake. I was testing on the first project I downloaded. I cloned this project again and now the breadcrumbs are showing correctly in the Crash Reporting dashboard.

Thank you for the follow-up.

**Comment by mduncan26** [comment]
No problem @albertoms. Let us know if you encounter any other issues.
